apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webfind

resources:
  - namespace.yaml
  - shared-pvc.yaml
  - redis.yaml
  - surrealdb.yaml
  - proxy-pool.yaml
  - webfind.yaml
  - crawl-job.yaml

commonLabels:
  app.kubernetes.io/part-of: webfind
